// Generated by Copilot
module WeeklyCalendar.Views.Components.ConfigView

open Giraffe.ViewEngine

let closedView = div [ _id "config-box" ; _class "hidden" ] []

let view () =    
    div [ _class "card position-absolute shadow"; _style "width: 300px; top: 50px; right: 20px; z-index: 1000" ] [
        div [ _class "card-header d-flex justify-content-between align-items-center" ] [
            h5 [ _class "card-title mb-0" ] [ str "Settings" ]
            button [
                _type "button"
                _class "btn-close"
                attr "hx-get" "/api/config/close"
                attr "hx-target" "#config-box"
            ] []
        ]
        div [ _class "card-body" ] [
            ul [] [
                li [] [
                    button [
                        _id "activate"
                        _class "btn btn-link p-0"
                    ] [ str "Disable Standby" ]                    
                ]
            ]
        ]
    ]

