// Generated by Copilot
module WeeklyCalendar.Views.Components.DateTimePanel

open Giraffe.ViewEngine
open System
open WeeklyCalendar.Domain

let dateTimePanel (getWeather: GetWeather) =
    let weather = getWeather () |> Async.AwaitTask |> Async.RunSynchronously
    let night = 
        weather.Forecast.ForecastDay
        |> Seq.tryHead
        |> function
        | Some d when DateTime.Now.Hour < d.astro.SunriseHour || DateTime.Now.Hour >= d.astro.SunsetHour -> true
        | _ -> false

    div [ _id "date-time-panel"
          _class (sprintf "date-time-panel p-2 border-bottom %s" (if night then "bg-dark text-light" else "bg-light")) ] [
        div [ _class "d-flex justify-content-between align-items-center" ] [
            div [ _class "date-display h4 mb-0" ] [
                button [
                    _class "btn btn-link p-0 mb-2"
                    attr "hx-get" "/api/config"
                    attr "hx-target" "#config-box"
                ] [
                    str (DateTime.Now.ToString("ddd, MMM dd"))
                ]                
            ]
            ConfigView.closedView
            TimeDisplay.timeDisplay ()
        ]
    ]
