// Generated by Copilot
module WeeklyCalendar.Views.Components.TimeDisplay

open Giraffe.ViewEngine

let timeDisplay () =
    div [ _class "time-display" ] [
        span [ _id "current-time"; _class "current-time" ] []
        div [ _class "seconds-progress" ] [
            div [ _id "progress-bar"; _class "progress-bar"; _style "height: 2px; background: dark-grey" ] []
        ]
    ]
