// Generated by Copilot
module WeeklyCalendar.Views.MainView

open Giraffe.ViewEngine
open WeeklyCalendar.Views.Components.DateTimePanel
open WeeklyCalendar.Views.Components.DailyAgenda

let mainView config =
    html [] [
        head [] [
            title [] [ str "Weekly Calendar" ]
            link [ _rel "stylesheet"
                   _href "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" ]
            link [ _rel "stylesheet"
                   _href "./css/app.css" ]
        ]
        body [] [
            div [ _class "container-fluid p-0 main-container" ] [
                // Section A: Date Time Panel
                dateTimePanel ()
                
                // Section B & C: Main content
                div [ _class "row m-0 content-row" ] [
                    div [ _class "col-9 p-2" ] [
                        // Photo slideshow will go here
                        str "Photo Slideshow"
                    ]
                    div [ _class "col-3 p-2 agenda-container" ] [
                        dailyAgenda config
                    ]
                ]
            ]
            script [_src "/js/app.js"] []
        ]
    ]
