// Generated by Copilot
module WeeklyCalendar.Handlers

open Giraffe
open WeeklyCalendar.Views.Components
open WeeklyCalendar.Views.MainView

let mainHandler config: HttpHandler =
    fun next ctx ->
        htmlView (mainView config) next ctx

let apiHandler: HttpHandler =
    let handlePhoto: HttpHandler =
        fun next ctx -> htmlView (PhotoFrame.photoFrame ()) next ctx
    choose [
        route "/photo" >=> handlePhoto
        route "/config" >=> (fun next ctx -> (htmlView (ConfigView.view ()) next ctx))
        route "/config/close" >=> (fun next ctx -> (htmlView ConfigView.closedView next ctx))
    ]
    