name: Docker Publish

on:
  workflow_dispatch:
  
env:
  IMAGE_NAME: my-agenda

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_TOKEN }}
      - name: Extract build number
        id: build_number
        run: echo "::set-output name=build_number::$(date +%s)"
  
      - name: Build and push Docker image
        run: |
          docker build \
           -t ghcr.io/jon-peel/my-agenda:latest \
           -t ghcr.io/jon-peel/my-agenda:${{ steps.build_number.outputs.build_number }} \
           --push \
           .